version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <secret>
      MYSQL_DATABASE: <db_name>
      MYSQL_PASSWORD: <secret>
      MYSQL_USER: <user>
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: